### ISSUE TITLE
Unsound call to `ReadConsoleInputW`

### ISSUE THREAD

**Issue by yescallop** [cfsamson/press-btn-continue#1]
According to [MS Docs](https://docs.microsoft.com/en-us/windows/console/readconsoleinput), the `buffer` parameter of `ReadConsoleInputW` takes a pointer to an array of `INPUT_RECORD` structures. It may probably be UB to call this extern function with a `[u8; 1]` as a buffer.

**Comment by cfsamson** [comment]
Good catch. Seems you're right. While I can't judge the size of `INPUT_RECORD` at a glance, it seems to be at least larger than a `u8` so that could probably cause the OS to overwrite the stack space.

As i see it there are two options:

A: find the maximum size of `INPUT_RECORD` and allocate that instead of just an `u8` (we don't care about the data so just calculating the required number of bytes and allocate `[u8; INPUT_RECORD_SIZE]` should suffice)
B: Pull inn Winapi as a dependecy and use their definition of [INPUT_RECORD](https://docs.rs/winapi/latest/winapi/um/wincontypes/struct.INPUT_RECORD.html) and allocate one of that instead of a `u8` (should be able to add a minimum to compile times by just enabling the `wincontypes` feature).

I'll have to find time to sit down soon and fix this as it should be a high priority to avoid potential problems.

**Comment by yescallop** [comment]
Thanks for quick response! I have already finished a fix and will soon create a pull request for your review.

**Comment by cfsamson** [comment]
No problem, glad you caught the error. A PR would be greatly appreciated! I'll prioritize the review so we get the fix out :)
